[pytest]
#addopts = -q
# addopts = --alluredir=allure-results

markers =
    login: Tests de autenticación y login
    smoke: Tests críticos de smoke
    regression: Suite completa de regresión
    critical: Funcionalidad crítica del negocio
    positive: Casos de prueba positivos
    negative: Casos de prueba negativos
    ui: Tests de interfaz de usuario
    e2e: Tests end-to-end
    parametrized: Tests parametrizados

testpaths = tests
python_files = test_*.py *_test.py
python_functions = test_*
python_classes = Test*
